# Generated by Django 2.2.2 on 2019-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191024_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='extras',
            field=models.ManyToManyField(to='services.Extras'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sheettypes',
            field=models.ManyToManyField(to='services.SheetTypes'),
        ),
    ]
