# Generated by Django 2.2.2 on 2019-11-19 18:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import project.apps.quotes.models
import project.apps.quotes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('numbercopies', models.BinaryField(max_length=255)),
                ('numbersets', models.BinaryField(max_length=255)),
                ('sheetsizes', models.CharField(max_length=255)),
                ('sheettypes', models.CharField(max_length=255)),
                ('extras', models.CharField(max_length=255)),
                ('observations', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=project.apps.quotes.models.path_and_rename, validators=[project.apps.quotes.validators.validate_file_extension])),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('enterprise', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('home_service', models.BooleanField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
