# Generated by Django 2.2.2 on 2019-11-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_specs'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='home_service',
            field=models.BooleanField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='id_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Services'),
            preserve_default=False,
        ),
    ]
