# Generated by Django 2.2.2 on 2019-11-11 21:44

from django.db import migrations, models
import project.apps.quotes.models
import project.apps.quotes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20191111_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='file',
            field=models.FileField(upload_to=project.apps.quotes.models.path_and_rename, validators=[project.apps.quotes.validators.validate_file_extension]),
        ),
    ]
