# Generated by Django 2.2.2 on 2019-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20190527_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enterprise',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='algo', max_length=255),
            preserve_default=False,
        ),
    ]
