# Generated by Django 2.2.2 on 2019-10-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_auto_20191031_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='merida', max_length=255),
            preserve_default=False,
        ),
    ]
