# Generated by Django 2.2.2 on 2019-10-21 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.apps.media_slides.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to=project.apps.media_slides.models.path_and_rename)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_slides_slides_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['-created_at'],
            },
        ),
    ]
