# Generated by Django 2.2.2 on 2019-11-19 18:43

from django.db import migrations, models
import project.apps.media_slides.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to=project.apps.media_slides.models.path_and_rename)),
            ],
            options={
                'verbose_name': 'Media Slide',
                'verbose_name_plural': 'Media Slides',
                'ordering': ['-created_at'],
            },
        ),
    ]
